parse classfile to extract inner class info
Fixes sbt/sbt#117
Inside `ClassToAPI`, Java reflection is used to calculate the inner classes. Under certain circumstances this fails to load some of the classes and result to a `NoClassDefFoundError`.
I've switched to parse the classfile manually, and wrapped `cl.loadClass` with a try-catch. I was able to confirm the fix using https://github.com/duboisf/sbt_issue_117_example