Restore binary compatibility of ClassFileManager
With sbt 1.4.0-M2, the swoval scala.js project cannot compile because of
the removal of the file based delete method from ClassFileManager:

[error] ## Exception when compiling 27 sources to
${SWOVAL_LOCATION}/nio-js/.js/target/scala-2.12/classes
[error] java.lang.NoSuchMethodError: 'void
xsbti.compile.ClassFileManager.delete(java.io.File[])'
[error]
org.scalajs.sbtplugin.SBTCompat$$anon$1.delete(SBTCompat.scala:49)

To get the swoval build to work, I restored but deprecated the delete
and generate methods in ClassFileManger. I also had to add default
implementations of the VirtualFile versions of these methods. The
defaults work by converting the virtual files to regular files and
invoking the legacy apis that take file arguments.