Fixes the reflection fallback for ScalaInstance
I think I've made a mistake in https://github.com/sbt/zinc/pull/505 by using NoSuchMethodError. When trying to use Zinc 1.1.2, I ran into `java.lang.NoSuchMethodException`.
This is because `NoSuchMethodException` would be thrown for reflective calls, not `NoSuchMethodError`.